### ISSUE TITLE
FormData support

### ISSUE THREAD

**Issue by MeloJR** [posva/mande#26]
I have searched in the code but I think it is impossible to send correctly a request with a `FormData`. `fetch` sends it correctly if you pass no `Content-Type` header but with mande you can't delete this header in a specific request. Are there any solution to this problem?

**Comment by posva** [comment]
I imagine you could pass `undefined` to `Content-Type` header when creating a `mande` instance.

If not, you can also delete it from the defaults:

```js
import { defaults } from 'mande'

delete defaults.headers['Content-Type']
```

The thing, we call JSON.stringify on it later: https://github.com/posva/mande/blob/master/src/index.ts#L210,
So it requires stringifying the value. There seem to be multiple ways of sending FormData. What are you doing?

**Comment by ephes** [comment]
Hi, thanks for this cool library!

While trying to login to an api I stumbled upon this just now. Is it possible to send a raw string as body with mande? Because my token endpoint wont accept a string containing '"' from JSON.stringify..

best regards,
jochen

**Comment by posva** [comment]
You can pass a string to `mandeInstance.push('some text')` but you will need to set the correct `Content-type` depending on what the endpoint is expected.

**Comment by ephes** [comment]
Thanks a lot, this worked! My code now looks like this:
```typescript
      const settings = useSettings();
      let formData = new FormData();
      formData.append("username", this.username);
      formData.append("password", this.password);
      const body =
        "grant_type=password&" + new URLSearchParams(formData as any).toString();
      const client = mande(settings.api);
      const options = client.options as any;
      options["body"] = body;
      client.options.headers["Content-Type"] =
        "application/x-www-form-urlencoded";
      client
        .post<{ access_token: string }>("/token")
        .then((response) => {
          console.log("response: ", response);
          this.accessToken = response.access_token;
          if (this.isAuthenticated) {
            this.onLoginSuccess();
          }
        })
        .catch(() => {
          // response.json().detail is not included -> use own error message
          this.errorMessage = "Incorrect username or password";
        });

```

**Comment by michaelnwani** [comment]
@posva Hi!

I'm not sure that it's possible to actually delete the default headers, and to send form data using a `multipart/form-data` header content type.

When I delete the default mande headers, my form data payload is defaulting to `text/plain; charset=utf-8`.
When I set `headers: undefined` in the options argument, it defaults to `application/json`.

It it helps/makes any difference, I'm trying to send a file `Blob` value in the form data
