### ISSUE TITLE
Question: Anyway to get error message which is returned by server

### ISSUE THREAD

**Issue by buenyaminyilmaz** [posva/mande#307]
Hi there,
i am trying to use mande. 
Is there any way to catch the error is given from server.
For an example:
```
 try {
          const response = await registerApi.post({
            email: this.email,
            password: this.password,
            passwordConfirmed: this.passwordRepeat,
          })

          resolve(response)
        } catch (error) {
          console.log('ServerError', error)
          reject(error)
        }
```
`registerApi` is a mande instance. The server returns for me i this case `422 (Unprocessable Entity)` and an error message.
So how can i show this error message? `console.log('ServerError', error)` shows `ServerError Error: Unprocessable Entity`.
Thank you in advance

**Comment by wizbit** [comment]
The error contains 2 extra items, `response` & `data`.
I would handle the server error like this

```js
 try {
   const response = await registerApi.post({
     email: this.email,
     password: this.password,
     passwordConfirmed: this.passwordRepeat,
   })
   resolve(response)
} catch (error) {
  console.log('ServerError', await error.response.json())
  reject(error)
}
```

**Comment by wizbit** [comment]
`error.body` might contain the data you are after.

**Comment by alexey-us** [comment]
Thanks!

**Comment by johannesronaldsson** [comment]
Interesting... so I get nothing back, while the response gives JSON back. Not quite sure what's going on here... Love the library btw.

[](url
<img width="680" alt="Screenshot 2022-04-12 at 16 14 21" src="https://user-images.githubusercontent.com/26920513/163007422-1cbbc4b5-e1f4-47ff-9d41-30f90bc3c887.png">

<img width="372" alt="Screenshot 2022-04-12 at 16 13 00" src="https://user-images.githubusercontent.com/26920513/163007413-60bdc9f2-68a3-4953-96b4-702275374589.png">
<img width="559" alt="Screenshot 2022-04-12 at 16 13 07" src="https://user-images.githubusercontent.com/26920513/163007420-9b7f2f37-a3fd-4278-861c-55b6925ae700.png">
)

**Comment by koficoud** [comment]
@johannesronaldsson You can access to the data using: `error.body`

```js
try {
  const login = await api.post(apiUri, credentials);
} catch (error) {
  console.error(error.body)
}
```

**Comment by bk973** [comment]
Was this issue resolved?
@buenyaminyilmaz  were the responses helpful

**Comment by buenyaminyilmaz** [comment]
Hi there, i will just test it out.
i switched to axios, because i was in hurry

**Comment by posva** [comment]
I created https://github.com/posva/mande/issues/378 to track
