### ISSUE TITLE
Not adding trailing '/' to request

### ISSUE THREAD

**Issue by panmenghan** [posva/mande#328]
```js
const rpc = mande('/rpc/endpoint')

rpc.post({some_rpc_name, ...}) // -> mande will always add trailing `/`, so the request path change to `/rpc/endpoint/`
```
My use case is the server has only one endpoint to serve all the requests(not REST API), my current workaround was let the server to listen to `/rpc/endpoint` and `/rpc/endpoint/` both. 

May add a option to disable adding the trailing `/` to the request path?

**Comment by dmix** [comment]
this is a major recurring problem for me. Any chance we could get it merge? It would be much appreciated :D
