### ISSUE TITLE
[Feature Request] Support JSON.stringify replacer function

### ISSUE THREAD

**Issue by michaelnwani** [posva/mande#382]
Firstly, thank you for making mande and continuing to support it 🙂 this is the best fetch library available. I really appreciate it.

My proposal here is to add a config option for dev's to pass a replacer function to the `JSON.stringify` that is used when making API calls. This would really help when resolving cyclic reference issues.

Example inspired from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value):

```js
const replacer = () => {
  const seen = new WeakSet();
  return (key, value) => {
    if (typeof value === "object" && value !== null) {
      if (seen.has(value)) {
        return;
      }
      seen.add(value);
    }
    return value;
  };
};

JSON.stringify(circularReference, replacer());
```

Maybe we can set it during the mande initialization, so it would look something like:

```js
import { mande } from 'mande'
const users = mande('/api/users',{replacer})
```

**Comment by posva** [comment]
Maybe even allow a custom `JSON.sringify()`
