### ISSUE TITLE
Mande sets Content-Type: application/json for simple get requests.

### ISSUE THREAD

**Issue by Higher08** [posva/mande#396]
When using for simple GET request, like this:
`await api.get('group/' + groupId + '/channels')`
Mande sets Content-Type header with unsafe value of application/json, which issues preflight request.
GET requests shouldn't have a body, so I think that header is unnecessary or at least optional.
Can you fix this?

**Comment by posva** [comment]
You can set a different default header if you want or do it per request. https://github.com/posva/mande#usage
