### ISSUE TITLE
Couldn't find module declaration types

### ISSUE THREAD

**Issue by Guilledll** [posva/mande#401]
## Importing error :x: 

Hello, I just installed the package on my new `vite + vue 3` project at vsCode, i'm using `"typescript": "^5.1.3"`, the following error appeared:

```txt
Could not find a declaration file for module 'mande'. '/home/guille/code/vue/node_modules/mande/dist/mande.mjs' implicitly has an 'any' type.
  There are types at '/home/guille/code/vue/node_modules/mande/dist/mande.d.ts', but this result could not be resolved when respecting package.json "exports". The 'mande' library may need to update its package.json or typings.
``` 

![image](https://github.com/posva/mande/assets/54317276/42d9fcb6-c87f-467f-9ef1-dad4dabec7a3)

### Reproduccion repo :open_file_folder:
https://github.com/Guilledll/mande-type-issue

Is this something I can fix updating some package or changing my **tsconfig.json** or is an error from the **mande package**?

Thanks in advance! :raised_hands:

**Comment by DevMoritz** [comment]
I have the same problem. But I cant find a solution.
