### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED when trying to use nuxt 2 module

### ISSUE THREAD

**Issue by ceigh** [posva/mande#474]
Hi, first of all, thanks for the cool module!

I'm trying to implement it in my nuxt 2 project, I got to the point about connecting the module to buildModules: https://github.com/posva/mande?tab=readme-ov-file#nuxt-2

```js
// nuxt.config.js
module.exports = {
  buildModules: ['mande/nuxt'],
}
```

But it looks like something is wrong with the `exports` in the package, and I can't run the `build` (or `dev`):

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './nuxt' is not defined by "exports" in /home/projects/mande-nuxt/node_modules/mande/package.json
```

| Package | Version |
| ------- | ------- |
| mande   | 2.0.9   |
| nuxt    | 2.17.3  |
| node    | 20.13.1 |

Here's a small reproduction: https://stackblitz.com/edit/mande-nuxt ✌️

**Comment by posva** [comment]
Sorry for the delay, I don't use nuxt 2 anymore and it's already reached EOL so I won't be able to give this time. I will probably remove the Nuxt 2 section from the readme in the near future.
